-- Fichier de création de la base de données 
BEGIN;

DROP TABLE IF EXISTS "country" CASCADE;
DROP TABLE IF EXISTS "coffee" CASCADE;
DROP TABLE IF EXISTS "coffee_characteristic" CASCADE;
DROP TABLE IF EXISTS "characteristic" CASCADE;

CREATE TABLE IF NOT EXISTS "country" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "coffee" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    "reference" CHAR(9) NOT NULL UNIQUE, 
    "name" TEXT, 
    "country_id" INT NOT NULL REFERENCES "country"("id"),
    "description" TEXT, 
    "price" NUMERIC, 
    "disponibility" BOOLEAN,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
); 


CREATE TABLE IF NOT EXISTS "characteristic" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "coffee_characteristic" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "characteristic_id" INT NOT NULL REFERENCES "characteristic"("id"),
    "coffee_id" INT NOT NULL REFERENCES "coffee"("id")
);

INSERT INTO "country" ("name") VALUES
('Italie'),
('Colombie'),
('Éthiopie'),
('Brésil'),
('Guatemala'),
('Kenya'),
('Indonésie'),
('Costa Rica'),
('Vietnam'),
('Tanzanie'),
('Jamaïque'),
('Rwanda'),
('Panama'),
('Pérou'),
('Hawaï'),
('Nicaragua');


INSERT INTO "coffee" ("reference", "name", "country_id", "description", "price", "disponibility") VALUES
('100955890', 'Expresso', 1, 'Café fort et concentré préparé en faisant passer de l''eau chaude à travers du café finement moulu.', 20.99, TRUE),
('100955894', 'Columbian', 2, 'Café moyennement corsé avec une acidité vive et une saveur riche.', 18.75, TRUE),
('105589090', 'Ethiopian Yirgacheffe', 3, 'Réputé pour son arôme floral, son acidité vive et ses notes de saveur citronnée.', 22.50, TRUE),
('134009550', 'Brazilian Santos', 4, 'Café doux et lisse avec un profil de saveur de noisette.', 17.80, TRUE),
('256505890', 'Guatemalan Antigua', 5, 'Café corsé avec des nuances chocolatées et une pointe d''épice.', 21.25, TRUE),
('295432730', 'Kenyan AA', 6, 'Café complexe connu pour son acidité rappelant le vin et ses saveurs fruitées.', 23.70, TRUE),
('302932754', 'Sumatra Mandheling', 7, 'Café profond et terreux avec un corps lourd et une faible acidité.', 19.95, TRUE),
('327302954', 'Costa Rican Tarrazu', 8, 'Café vif et net avec une finition propre et une acidité vive.', 24.50, TRUE),
('549549090', 'Vietnamese Robusta', 9, 'Café audacieux et fort avec une saveur robuste distinctive.', 16.75, TRUE),
('582954954', 'Tanzanian Peaberry', 10, 'Acidité vive avec un profil de saveur rappelant le vin et un corps moyen.', 26.80, TRUE),
('589100954', 'Jamaican Blue Mountain', 11, 'Reconnu pour sa saveur douce, son acidité vive et son absence d''amertume.', 39.25, TRUE),
('650753915', 'Rwandan Bourbon', 12, 'Café avec des notes florales prononcées, une acidité vive et un corps moyen.', 21.90, TRUE),
('795501340', 'Panamanian Geisha', 13, 'Café rare aux arômes floraux complexes, une acidité brillante et un profil de saveur distinctif.', 42.00, TRUE),
('954589100', 'Peruvian Arabica', 14, 'Café équilibré avec des notes de chocolat, une acidité modérée et un corps velouté.', 19.40, FALSE),
('958090105', 'Hawaiian Kona', 15, 'Café rare au goût riche, une acidité douce et des nuances subtiles.', 55.75, FALSE),
('691550753', 'Nicaraguan Maragogipe', 16, 'Café avec des notes de fruits, une acidité vive et un corps plein.', 28.60, FALSE);


INSERT INTO "characteristic" ("name") VALUES
('Corsé'),
('Fruité'),
('Boisé'),
('Épicé'),
('Floral'),
('Acidulé'),
('Léger'),
('Herbacé'),
('Chocolaté');

-- Expresso (100955890)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Corsé'
  AND "coffee"."reference" = '100955890';

INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Épicé'
  AND "coffee"."reference" = '100955890';


-- Columbian (100955894)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Acidulé'
  AND "coffee"."reference" = '100955894';


-- Ethiopian Yirgacheffe (105589090)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Léger'
  AND "coffee"."reference" = '105589090';

INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Fruité'
  AND "coffee"."reference" = '105589090';


-- Brazilian Santos (134009550)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Léger'
  AND "coffee"."reference" = '134009550';


-- Guatemalan Antigua (256505890)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Corsé'
  AND "coffee"."reference" = '256505890';


-- Kenyan AA (295432730)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Léger'
  AND "coffee"."reference" = '295432730';

INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Acidulé'
  AND "coffee"."reference" = '295432730';


-- Sumatra Mandheling (302932754)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Corsé'
  AND "coffee"."reference" = '302932754';


-- Costa Rican Tarrazu (327302954)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Acidulé'
  AND "coffee"."reference" = '327302954';


-- Vietnamese Robusta (549549090)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Épicé'
  AND "coffee"."reference" = '549549090';


-- Tanzanian Peaberry (582954954)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Fruité'
  AND "coffee"."reference" = '582954954';

INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Corsé'
  AND "coffee"."reference" = '582954954';


-- Jamaican Blue Mountain (589100954)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Léger'
  AND "coffee"."reference" = '589100954';


-- Rwandan Bourbon (650753915)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Fruité'
  AND "coffee"."reference" = '650753915';


-- Panamanian Geisha (795501340)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Fruité'
  AND "coffee"."reference" = '795501340';


-- Peruvian Arabica (954589100)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Corsé'
  AND "coffee"."reference" = '954589100';

INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Chocolaté'
  AND "coffee"."reference" = '954589100';


-- Hawaiian Kona (958090105)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Léger'
  AND "coffee"."reference" = '958090105';


-- Nicaraguan Maragogipe (691550753)
INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Corsé'
  AND "coffee"."reference" = '691550753';

INSERT INTO "coffee_characteristic" ("characteristic_id", "coffee_id")
SELECT "characteristic"."id", "coffee"."id"
FROM "characteristic", "coffee"
WHERE "characteristic"."name" = 'Fruité'
  AND "coffee"."reference" = '691550753';


COMMIT;
